/home/ariis-pc/dev/ArenaViewMP_v_1.0.0.10_Linux_x64/ArenaSDK_Linux_x64/lib64
/home/ariis-pc/dev/ArenaViewMP_v_1.0.0.10_Linux_x64/ArenaSDK_Linux_x64/GenICam/library/lib/Linux64_x64
/home/ariis-pc/dev/ArenaViewMP_v_1.0.0.10_Linux_x64/ArenaSDK_Linux_x64/ffmpeg
/home/ariis-pc/dev/ArenaViewMP_v_1.0.0.10_Linux_x64/ArenaSDK_Linux_x64/Metavision/lib
/home/ariis-pc/dev/ArenaViewMP_v_1.0.0.10_Linux_x64/ArenaSDK_Linux_x64/OpenCV/lib